### ISSUE TITLE
event.layer.setStyle is not a function error for POINT geometries

### ISSUE THREAD

**Issue by dkintgen** [radiantearth/stac-browser#554]
I have a Collection with a set of Items that are POINT geometries:

![Image](https://github.com/user-attachments/assets/a006c95d-d2a9-4a3e-952c-821cd42ec669)

If I click on one of the blue flags, I get this error:

![Image](https://github.com/user-attachments/assets/a51d782f-6ae3-4aed-a0e0-59f1b114d282)

It works in 3.2.0 but not 3.3.0.  My Collections that have MULTIPOLYGON   I have found a section of Map.vue file that can be commented out to "fix" this issue, but I am not sure what other unintended consequences I am causing by commenting these lines out:

`          if (event.layer) {
            this.selectedItem.oldStyle = Object.assign({}, event.layer.options);
            event.layer.setStyle(Object.assign({}, event.layer.options, {color: '#dc3545'}));
          }`

None of the changes from 3.2.0 -> 3.3.0 seem to have directly caused this.  Can anyone tell me why this started happening or what problems I will be causing by commenting out the above lines of code in Map.vue?

**Comment by m-mohr** [comment]
Thanks for the report.

Can you send me the STAC file, please? I'd like to reproduce it and also check whether this case is covered by the new OL-based mapping approach, see.#535 

If you can't attach it here, you can send it also via email (see profile).

**Comment by dkintgen** [comment]
https://stac-api.aws.chesapeakebay.net/collections/data-by-station/ is the API for the collection, is that enough?

**Comment by m-mohr** [comment]
I've fixed this to not set a Style for Point layers, which work with icons instead of styles. Drawback is that it doesn't highlight the selected entity, but given that #535 is soon ready, I also don't want to invest too much time into this.
